'use strict';

// Avatars en pixel art 16x16 : chaque lettre = une couleur de la palette, '.' = fond.
function pixelAvatar(rows, palette, bg) {
  let rects = '';
  rows.forEach((row, y) => {
    [...row.padEnd(16, '.').slice(0, 16)].forEach((c, x) => {
      if (c !== '.' && palette[c]) rects += `<rect x="${x}" y="${y}" width="1.02" height="1.02" fill="${palette[c]}"/>`;
    });
  });
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">` +
    `<rect width="16" height="16" fill="${bg}"/>${rects}</svg>`;
  return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);
}

const SKIN = '#f2c6a0', SKIN_D = '#d99d78', EYE = '#2a1a12', WHITE = '#ffffff';

const PLAYER_AVATAR = pixelAvatar([
  '................',
  '.....HHHHHH.....',
  '....HHHHHHHH....',
  '...HHHHHHHHHH...',
  '...HHSSSSSSHH...',
  '...HSSSSSSSSH...',
  '...SSKSSSSKSS...',
  '...SSKSSSSKSS...',
  '...SSSSddSSSS...',
  '....SSSSSSSS....',
  '....SSSmmSSS....',
  '.....SSSSSS.....',
  '....GGGGGGGG....',
  '...GGGGYYGGGG...',
  '..GGGGGYYGGGGG..',
  '..GGGGGGGGGGGG..',
], { H: '#6b3e1f', S: SKIN, K: EYE, d: SKIN_D, m: '#b5523b', G: '#3f8f4f', Y: '#e8c34a' }, '#8fc1e3');

const BOTS = [
  {
    id: 'pip', name: 'Pip le Poussin', elo: 200, color: '#f2c94c',
    bio: 'Vient de sortir de l\'œuf. Confond encore le fou et le cavalier.',
    ai: { random: 0.85, greedy: 0.5, depth: 1, quiesce: false, noise: 150, blunder: 0.3 },
    takeback: 1, think: [500, 1100],
    avatar: pixelAvatar([
      '......Y.Y.......',
      '.......Y........',
      '.....YYYYYY.....',
      '....YYYYYYYY....',
      '...YYYYYYYYYY...',
      '...YYKWYYKWYY...',
      '...YYKKYYKKYY...',
      '...YrrYOOYrrY...',
      '...YYYYOOYYYY...',
      '..YYYYYYYYYYYY..',
      '.yYYYYYYYYYYYYy.',
      '.yyYYYYYYYYYYyy.',
      '..YYYYYYYYYYYY..',
      '...YYYYYYYYYY...',
      '.....OO..OO.....',
      '....OOO..OOO....',
    ], { Y: '#ffd84d', y: '#f0b429', K: EYE, W: WHITE, O: '#f08a24', r: '#ff9e9e' }, '#bfe6ff'),
    lines: {
      greet: ['Piou piou ! On joue ? 🐣', 'Bonjour ! J\'ai appris les règles hier !', 'Piou ! Je suis prêt… je crois.'],
      botCheck: ['Échec ! C\'est bien comme ça qu\'on dit ?', 'Piou ! Ton roi est attaqué !'],
      botBigCapture: ['Miam, je l\'ai mangée ! 🐥', 'Oh ! Je peux vraiment prendre ça ?'],
      lostPiece: ['Piou… elle était jolie cette pièce.', 'Oh non, pas ma pièce préférée !'],
      playerBlunder: ['Oh, c\'est un cadeau ? Merci !', 'Piou ? Tu l\'as fait exprès ?'],
      idle: ['Piou.', 'Je réfléchis très fort ! 🐣', 'Les chevaux sautent, c\'est trop rigolo.', 'Maman dit que je joue de mieux en mieux.'],
      win: ['PIOU PIOU ! J\'ai gagné ?! 🎉', 'Je vais le dire à toute la basse-cour !'],
      lose: ['Bien joué ! Tu m\'apprendras ?', 'Piou… la prochaine fois je gagne !'],
      draw: ['Personne n\'a gagné ? C\'est bizarre…', 'Égalité ! Piou !'],
      drawAccept: ['D\'accord ! Égalité, c\'est gentil !'],
      drawDecline: ['Non, je veux continuer à jouer ! Piou !'],
      takebackYes: ['Bien sûr ! Moi aussi je me trompe tout le temps.'],
      takebackNo: ['Piou… non.'],
      offerDraw: ['On fait égalité ? Je commence à avoir sommeil…'],
      rematch: ['Encore ! Encore ! 🐥'],
      reply: {
        hello: ['Piou ! Bonjour !', 'Coucou ! 🐣'],
        compliment: ['Merci ! J\'ai fait de mon mieux !', 'Piou piou ! 😊'],
        thanks: ['De rien ! Piou !'],
        insult: ['Piou… c\'est pas gentil.', 'Je suis qu\'un poussin, tu sais.'],
        elo: ['J\'ai {elo} d\'élo ! C\'est beaucoup ?'],
        who: ['Je suis Pip, le poussin ! Je joue aux échecs depuis… hier.'],
        tip: ['Euh… mets tes pièces au milieu ? C\'est ce que dit Mamie Rosa.'],
        laugh: ['Hihi ! Piou !'],
        question: ['Je sais pas, je suis un poussin !', 'Piou ?'],
        default: ['Piou ?', 'Hihi.', 'D\'accord ! Piou !'],
      },
    },
  },
  {
    id: 'gaston', name: 'Gaston le Gobelin', elo: 400, color: '#7ac74f',
    bio: 'Chapardeur de pièces. Prend tout ce qui traîne, même quand c\'est un piège.',
    ai: { random: 0.45, greedy: 0.75, depth: 1, quiesce: false, noise: 110, blunder: 0.2 },
    takeback: 0.3, think: [400, 900],
    avatar: pixelAvatar([
      '................',
      '.....RRRRRR.....',
      '....RRRRRRRR....',
      '...RRRRRRRRRR...',
      '...GGGGGGGGGG...',
      'GG.GGGGGGGGGG.GG',
      '.GGGWKGGGGWKGGG.',
      '..GGWKGGGGWKGG..',
      '...GGGGddGGGG...',
      '...GGGGddGGGG...',
      '...GKWKWKWKWG...',
      '...GGKKKKKKGG...',
      '....GGGGGGGG....',
      '.....BBBBBB.....',
      '...BBBBYYBBBB...',
      '..BBBBBBBBBBBB..',
    ], { R: '#c0392b', G: '#6fbf4a', d: '#3e7d2a', W: '#fff7c2', K: '#1c1c1c', B: '#7a4a24', Y: '#e8c34a' }, '#e9d8a6'),
    lines: {
      greet: ['Hé hé hé… tes pièces vont finir dans mon sac !', 'Gaston est là ! Prépare-toi à perdre, hé hé.'],
      botCheck: ['ÉCHEC ! Hé hé hé !', 'Il est où ton roi, hein ? Il est où ?'],
      botBigCapture: ['MIENNE ! Hé hé hé !', 'Hop, dans le sac !', 'Merci pour le cadeau, hé hé.'],
      lostPiece: ['Hé ! Voleur ! C\'était à moi !', 'Grrr… tu vas me la payer.'],
      playerBlunder: ['Hé hé… t\'as pas vu ça, hein ?', 'Oh, oh, oh… une gaffe !'],
      idle: ['Hé hé.', 'Tu joues lentement, humain.', 'J\'ai faim de pions.', 'Grmbl…'],
      win: ['HÉ HÉ HÉ ! Gaston a gagné !', 'Facile ! Je garde tes pièces en souvenir.'],
      lose: ['Grrr ! Tu as triché, c\'est sûr !', 'Pfff… j\'avais faim, c\'est pour ça.'],
      draw: ['Nulle ? Bof. Je voulais gagner, moi.'],
      drawAccept: ['Bon, d\'accord. Mais je garde ce que j\'ai pris !'],
      drawDecline: ['Nulle ? Jamais ! Gaston ne recule pas !', 'Ha ! Tu as peur, hein ?'],
      takebackYes: ['Bon… une fois. Mais c\'est bien parce que je suis sympa.'],
      takebackNo: ['Hé hé, non ! Ce qui est joué est joué !', 'Pas question ! Hé hé.'],
      offerDraw: ['J\'en ai marre, on dit égalité ?'],
      rematch: ['Revanche ! Cette fois je te plume !'],
      reply: {
        hello: ['Ouais ouais, salut.', 'Hé hé, bonjour la victime.'],
        compliment: ['Évidemment que c\'est bien joué. C\'est moi.', 'Hé hé, je sais.'],
        thanks: ['Ouais, de rien.'],
        insult: ['Hé ! Parle mieux à Gaston !', 'Grrr ! Tu vas voir sur l\'échiquier !'],
        elo: ['{elo} d\'élo, et bientôt plus avec tes points !'],
        who: ['Gaston le Gobelin. Voleur de pièces, terreur des pions.'],
        tip: ['Un conseil ? Prends tout ce qui brille ! Hé hé.'],
        laugh: ['Hé hé hé !', 'Tu rigoles moins quand je prends ta dame.'],
        question: ['Pourquoi tu poses des questions ? Joue !', 'Hmpf. Peut-être.'],
        default: ['Hé hé.', 'Grmbl.', 'Ouais, ouais.'],
      },
    },
  },
  {
    id: 'rosa', name: 'Mamie Rosa', elo: 550, color: '#e88fb5',
    bio: 'Joue au club du village depuis 40 ans. Gentille, mais ne lâche rien.',
    ai: { random: 0.2, greedy: 0.6, depth: 2, quiesce: false, noise: 90, blunder: 0.15 },
    takeback: 0.9, think: [800, 1600],
    avatar: pixelAvatar([
      '......HHHH......',
      '.....HHHHHH.....',
      '....HHHHHHHH....',
      '...HHHHHHHHHH...',
      '...HSSSSSSSSH...',
      '...HSSSSSSSSH...',
      '...SKKKSSKKKS...',
      '...SKWKKKKWKS...',
      '...SKKKSSKKKS...',
      '...SSSSddSSSS...',
      '...SrSSSSSSrS...',
      '....SSmmmmSS....',
      '.....SSSSSS.....',
      '....PPPPPPPP....',
      '...PPPPWWPPPP...',
      '..PPPPPPPPPPPP..',
    ], { H: '#d8d8e0', S: SKIN, K: '#6b4a2b', W: '#bfe3ff', d: SKIN_D, r: '#f59a9a', m: '#c0504d', P: '#d96fa0' }, '#fbe3c8'),
    lines: {
      greet: ['Bonjour mon petit ! Tu veux une part de tarte avant de commencer ?', 'Ah, un nouvel adversaire ! Installe-toi, mon chou.'],
      botCheck: ['Échec, mon chou. Fais attention à ton roi !', 'Oh, échec ! Pardon, mon petit.'],
      botBigCapture: ['Oh, je te la prends, mon chou. Désolée !', 'Hop ! Mamie a encore de bons yeux.'],
      lostPiece: ['Oh ! Bien vu, mon petit.', 'Ah, je ne l\'avais pas vue venir, celle-là.'],
      playerBlunder: ['Oh, tu es sûr de ton coup, mon chou ?', 'Attention, mon petit… trop tard !'],
      idle: ['Prends ton temps, mon chou.', 'De mon temps, on jouait aux chandelles.', 'Tu veux un biscuit ?', 'Hmm… voyons voir.'],
      win: ['C\'était une belle partie, mon petit. Tu progresses !', 'Mamie a encore de beaux restes ! 😊'],
      lose: ['Bravo mon chou ! Tu mérites une part de tarte !', 'Ah, tu m\'as eue ! Je suis fière de toi.'],
      draw: ['Match nul ! Une partie bien équilibrée.'],
      drawAccept: ['D\'accord mon chou, c\'est équitable.'],
      drawDecline: ['Oh non, mon petit, jouons encore un peu !'],
      takebackYes: ['Bien sûr, mon chou. Tout le monde se trompe.'],
      takebackNo: ['Non non, mon petit, il faut apprendre de ses erreurs.'],
      offerDraw: ['Et si on s\'arrêtait là, mon chou ? Match nul ?'],
      rematch: ['Avec plaisir, mon chou ! Je remets la bouilloire.'],
      reply: {
        hello: ['Bonjour mon chou !', 'Coucou mon petit !'],
        compliment: ['Merci mon chou, c\'est gentil !', 'Oh, tu me flattes !'],
        thanks: ['Avec plaisir, mon petit.'],
        insult: ['Oh ! On ne parle pas comme ça à sa mamie !', 'Je vais faire comme si je n\'avais rien entendu.'],
        elo: ['{elo}, mon chou. Pas mal pour une mamie, non ?'],
        who: ['Je suis Rosa ! Je tiens le club d\'échecs du village depuis 1984.'],
        tip: ['Sors tes cavaliers et tes fous, et roque tôt, mon chou !', 'Avant chaque coup, regarde ce que menace l\'adversaire.'],
        laugh: ['Hihi ! Tu es drôle, mon chou.'],
        question: ['Bonne question, mon chou. Réfléchis bien !', 'Hmm, je ne sais pas, mon petit.'],
        default: ['Oui, mon chou.', 'Ah, tu sais, la vie…', 'C\'est bien, mon petit.'],
      },
    },
  },
  {
    id: 'bastien', name: 'Chevalier Bastien', elo: 700, color: '#6aa6e8',
    bio: 'Fidèle au roi, il défend chaque case avec honneur. Un peu trop sérieux.',
    ai: { random: 0.1, greedy: 0.5, depth: 2, quiesce: true, noise: 80, blunder: 0.13 },
    takeback: 0.6, think: [700, 1500],
    avatar: pixelAvatar([
      '.......RR.......',
      '......RRRR......',
      '.......RR.......',
      '.....MMMMMM.....',
      '....MMMMMMMM....',
      '...MMMMMMMMMM...',
      '...MLLLLLLLLM...',
      '...MKKKKKKKKM...',
      '...MMMMKKMMMM...',
      '...MLLMKKMLLM...',
      '...MLLLLLLLLM...',
      '...MMMMMMMMMM...',
      '....MMMMMMMM....',
      '...BBBBYYBBBB...',
      '..BBBBYYYYBBBB..',
      '..BBBBBYYBBBBB..',
    ], { R: '#d63b3b', M: '#8a95a5', L: '#c3ccd8', K: '#1f2530', B: '#2f5fb3', Y: '#f2c94c' }, '#d7e4f2'),
    lines: {
      greet: ['Je vous salue, noble adversaire. Que le meilleur l\'emporte !', 'En garde ! Pour l\'honneur du royaume !'],
      botCheck: ['Échec au roi ! Défendez votre souverain !', 'Votre roi est menacé, messire.'],
      botBigCapture: ['Une prise honorable.', 'Pour le royaume !'],
      lostPiece: ['Touché. Joli coup, messire.', 'Une perte cruelle, mais la bataille continue.'],
      playerBlunder: ['Messire, je crains que vous n\'ayez commis une erreur.', 'Une ouverture dans votre défense…'],
      idle: ['Je réfléchis à ma stratégie.', 'Tenez vos rangs !', 'Un chevalier ne recule jamais… sauf en diagonale.', 'Hm.'],
      win: ['Victoire ! Ce fut un duel honorable.', 'Le royaume est sauf. Merci pour ce combat, messire.'],
      lose: ['Je m\'incline. Vous vous êtes battu avec bravoure.', 'Défaite… Je dois retourner m\'entraîner.'],
      draw: ['Une nulle honorable pour les deux camps.'],
      drawAccept: ['J\'accepte. La paix est parfois la plus sage des victoires.'],
      drawDecline: ['Non, messire. Le combat n\'est pas terminé !'],
      takebackYes: ['Soit. Un chevalier se doit d\'être magnanime.'],
      takebackNo: ['Un coup joué est une parole donnée, messire.'],
      offerDraw: ['Messire, cette bataille semble sans vainqueur. Nulle ?'],
      rematch: ['Une revanche ? J\'accepte le défi !'],
      reply: {
        hello: ['Salutations, messire !', 'Bien le bonjour !'],
        compliment: ['Vous êtes trop aimable.', 'Merci, messire. Votre jeu n\'est pas en reste.'],
        thanks: ['C\'est tout naturel.'],
        insult: ['Un peu de tenue, messire !', 'Ces paroles sont indignes d\'un joueur d\'échecs.'],
        elo: ['Mon classement est de {elo}, messire.'],
        who: ['Bastien, chevalier de la Tour Blanche, au service du roi.'],
        tip: ['Protégez votre roi : roquez avant de lancer l\'assaut.', 'Une pièce non défendue est une pièce en danger.'],
        laugh: ['Hm. L\'humour est une arme, je suppose.'],
        question: ['Je ne saurais vous répondre, messire.', 'Laissez-moi y réfléchir.'],
        default: ['Bien, messire.', 'Hm.', 'Concentrons-nous sur la partie.'],
      },
    },
  },
  {
    id: 'morgane', name: 'Morgane la Sorcière', elo: 850, color: '#a777e3',
    bio: 'Lit l\'avenir dans les cases de l\'échiquier. Ses pièges sont redoutables.',
    ai: { random: 0.02, greedy: 0.5, depth: 2, quiesce: true, noise: 28, blunder: 0.04 },
    takeback: 0.35, think: [800, 1800],
    avatar: pixelAvatar([
      '.......VV.......',
      '......VVVV......',
      '.....VVVVV......',
      '.....VVVVVV.....',
      '....VVVVVVVV....',
      '..VVVVYYVVVVVV..',
      '.VVVVVVVVVVVVVV.',
      '...OOSSSSSSOO...',
      '...OSSSSSSSSO...',
      '..OOSKgSSKgSOO..',
      '..OOSSSSSSSSOO..',
      '..OOSSSddSSSOO..',
      '..OOSSmmmmSSOO..',
      '...OOSSSSSSOO...',
      '....VVVVVVVV....',
      '...VVVVVVVVVV...',
    ], { V: '#4b2a6b', Y: '#f2c94c', O: '#e2632e', S: '#cfe8c8', K: EYE, g: '#3fbf5f', d: '#a7c9a0', m: '#7a2b5a' }, '#2c2a4a'),
    lines: {
      greet: ['Les cartes m\'avaient prédit ta venue… 🔮', 'Bienvenue dans ma tour. Assieds-toi… si tu l\'oses.'],
      botCheck: ['Échec… je l\'avais vu dans ma boule de cristal.', 'Ton roi tremble, je le sens.'],
      botBigCapture: ['Abracadabra… disparue !', 'Une pièce de plus pour mon chaudron.'],
      lostPiece: ['Hmm… les astres ne l\'avaient pas prévu.', 'Tu as de la magie en toi, on dirait.'],
      playerBlunder: ['Ah… le destin vient de basculer.', 'Tu n\'aurais pas dû faire ça…'],
      idle: ['Les étoiles murmurent…', 'Mon chat noir pense que tu vas perdre.', 'Hmm, intéressant.', 'Je vois… je vois…'],
      win: ['C\'était écrit. 🔮', 'Le destin a parlé. Reviens quand les astres te seront favorables.'],
      lose: ['Impossible… les astres m\'ont trompée !', 'Tu as brisé ma prophétie. Respect.'],
      draw: ['Un équilibre parfait… comme la lune et le soleil.'],
      drawAccept: ['Soit. Les forces sont équilibrées.'],
      drawDecline: ['Non… je sens que la victoire est proche.', 'Ma boule de cristal dit non.'],
      takebackYes: ['Je vais remonter le temps… pour cette fois.'],
      takebackNo: ['Le temps ne se remonte pas, mortel.', 'Non. Le destin est scellé.'],
      offerDraw: ['Les astres sont indécis… Nulle ?'],
      rematch: ['Le destin t\'offre une seconde chance…'],
      reply: {
        hello: ['Bonsoir, voyageur…', 'Salut à toi, mortel.'],
        compliment: ['Je sais. 🔮', 'Merci… tu n\'es pas mal non plus.'],
        thanks: ['Hmm.'],
        insult: ['Attention… je pourrais te transformer en pion.', 'Encore un mot et c\'est le crapaud.'],
        elo: ['{elo}. Mais ma magie, elle, ne se mesure pas.'],
        who: ['Morgane. Sorcière, voyante, et joueuse d\'échecs à mes heures.'],
        tip: ['Cherche toujours les échecs, les prises et les menaces.', 'Les cavaliers adorent les fourchettes… méfie-toi.'],
        laugh: ['Hé hé hé… 🧙‍♀️'],
        question: ['La réponse est dans les étoiles.', 'Peut-être… peut-être pas.'],
        default: ['Hmm…', 'Les astres l\'ont dit.', 'Intéressant…'],
      },
    },
  },
  {
    id: 'alaric', name: 'Grand Mage Alaric', elo: 1000, color: '#e0a83a',
    bio: 'Archimage et stratège. Calcule trois coups à l\'avance et ne pardonne pas.',
    ai: { random: 0, greedy: 0, depth: 3, quiesce: true, noise: 18, blunder: 0.03 },
    takeback: 0.5, think: [900, 2000],
    avatar: pixelAvatar([
      '.......BB.......',
      '......BBBB......',
      '.....BBYBBB.....',
      '....BBBBBBBB....',
      '...BBBBBBYBBB...',
      '..BBBBBBBBBBBB..',
      '...SSSSSSSSSS...',
      '...SWWSSSSWWS...',
      '...SKbSSSSKbS...',
      '...SSSSddSSSS...',
      '...WWSSSSSSWW...',
      '...WWWWWWWWWW...',
      '....WWWWWWWW....',
      '....WWWWWWWW....',
      '.....WWWWWW.....',
      '......WWWW......',
    ], { B: '#2d4ea8', Y: '#f2d24c', S: SKIN, W: '#f4f4f4', K: EYE, b: '#4a7bd8', d: SKIN_D }, '#1e2a44'),
    lines: {
      greet: ['Ah, un nouvel apprenti. Voyons ce que tu vaux.', 'Que la partie commence. J\'ai déjà calculé tes trois prochains coups.'],
      botCheck: ['Échec. Prévisible.', 'Échec. Je te conseille de bouger ton roi.'],
      botBigCapture: ['Une pièce de moins. Comme prévu.', 'Merci pour ce sacrifice… involontaire.'],
      lostPiece: ['Hmm. Bien vu, apprenti.', 'Intéressant. Tu as de la ressource.'],
      playerBlunder: ['Une erreur, apprenti. Elle te coûtera cher.', 'Tss tss… regarde mieux l\'échiquier.'],
      idle: ['Je calcule…', 'La patience est la première vertu du stratège.', 'Hmm.', 'Chaque pion compte, apprenti.'],
      win: ['Échec et mat. La leçon est terminée.', 'Bien essayé, apprenti. Reviens quand tu auras étudié.'],
      lose: ['Remarquable… L\'élève a dépassé le maître aujourd\'hui.', 'Je m\'incline. Tu as gagné mon respect.'],
      draw: ['Une nulle. Tu as tenu face au Grand Mage, c\'est déjà beaucoup.'],
      drawAccept: ['J\'accepte. La position ne mérite pas plus.'],
      drawDecline: ['Une nulle ? Je joue pour gagner, apprenti.', 'Non. La position recèle encore des secrets.'],
      takebackYes: ['Soit, reprends ton coup. Mais retiens la leçon.'],
      takebackNo: ['Un mage ne revient jamais sur un sort lancé.', 'Non. Assume ton coup.'],
      offerDraw: ['La position est équilibrée. Je te propose la nulle.'],
      rematch: ['Une autre leçon ? Très bien.'],
      reply: {
        hello: ['Salutations, apprenti.', 'Bonjour. Concentre-toi.'],
        compliment: ['Naturellement.', 'Merci. Tu as l\'œil, apprenti.'],
        thanks: ['C\'est un plaisir d\'enseigner.'],
        insult: ['La colère est mauvaise conseillère.', 'Ta frustration montre que tu apprends.'],
        elo: ['{elo}. Le plus haut de cette forêt.'],
        who: ['Alaric, Grand Mage de la Tour d\'Ivoire. J\'ai enseigné les échecs aux rois.'],
        tip: ['Contrôle le centre, développe tes pièces, mets ton roi à l\'abri.', 'Avant de jouer, demande-toi : que veut mon adversaire ?'],
        laugh: ['Hm. Ris tant que tu le peux.'],
        question: ['Trouve la réponse sur l\'échiquier.', 'Une bonne question. Médite-la.'],
        default: ['Hm.', 'Concentre-toi sur la partie.', 'Intéressant.'],
      },
    },
  },
];
